# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171126_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commens_text',
            new_name='comments_text',
        ),
    ]
